apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: alpine-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: alpine
  placement:
    clusterAffinity:
      clusterNames:
        - kind-member1
        - kubernetes
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - kind-member1
            weight: 1
          - targetCluster:
              clusterNames:
                - kubernetes
            weight: 1